name: Games Education
favicon: null
layout_spectrum: 0.42756
typography_spectrum: 0.04994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5d188'
    - '#000000'
    - '#aa0000'
    - '#938b8d'
    - '#695100'
  brandStrength: 0.25
  lightness: 0.4371324856765568
  saturation: 0.6875
  rhythmicContrast: 0.9666630139108747
purpose: []
